### Get Home Page
GET http://localhost:5500/


### Build Diagnosis Form
GET http://localhost:5500/dg

### Submit Diagnosis Form
POST http://localhost:5500/dg
Content-Type: application/json

{
  "diagnosis": "Flu",
  "type": "Virus",
  "overview": "Influenza is a viral infection that attacks your respiratory system.",
  "symptoms": "Fever, chills, muscle aches, cough, congestion, runny nose, headaches, and fatigue.",
  "treatments": "Rest, fluids, antiviral medications.",
  "specialists": "General practitioner, Infectious disease specialist.",
  "contagiousMethod": "Airborne droplets, direct contact."
}


### Update Diagnosis (replace {id} with an actual diagnosis ID)
PUT http://localhost:5500/dg/update/66523e7eedbde7c95dd9b0df
Content-Type: application/json

{
  "diagnosis": "Updated Diagnosis",
  "type": "Updated Type",
  "overview": "Updated Overview",
  "symptoms": "Updated Symptoms",
  "treatments": "Updated Treatments",
  "specialists": "Updated Specialists",
  "contagiousMethod": "Updated Contagious Method"
}

### Delete Diagnosis (replace {id} with an actual diagnosis ID)
DELETE http://localhost:5500/dg/delete/66523e7eedbde7c95dd9b0df

### View All Diagnoses
GET http://localhost:5500/getalldg

### View Diagnosis By ID (replace {id} with an actual diagnosis ID)
GET http://localhost:5500/dg/665736822ce4e0ab20c1d67a

### Submission Success Page
GET http://localhost:5500/success